### ISSUE TITLE
Running with >= 3 models produces an incorrect total cross section in the event write out

### ISSUE THREAD

**Issue by nastein** [AchillesGen/Achilles#47]
When testing running with multiple models on the process grouping branch it was found that running with 3 models (Fortran QE, Interference, and Res) produces an incorrect total cross section. This did not occur when running with only two models at a time.

Run card is provided below: 

```
Main:
  NEvents: 100000
  HardCuts: true
  EventCuts: false
  DoRotate: false
  RunDecays: False
  Output:
      Format: NuHepMC
      Name: achilles_1108_37p5_total.hepmc
      Zipped: True

SherpaOptions:
  Model: SMnu
  ParamCard: parameters.dat

Processes:
  - Leptons: [11, [11]]

Initialize:
  Seed: 12345678
  Accuracy: 1e-2

Unweighting:
  Name: Percentile
  percentile: 99

Beams:
  - Beam:
      PID: 11
      Beam Params:
        Type: Monochromatic
        Energy: 1108

Cascade:
  Run: False
  Interaction:
    Name: GeantInteractions
    GeantData: data/GeantData.hdf5
  Step: 0.04
  Probability: Cylinder
  InMedium: None
  PotentialProp: False

NuclearModels:
  - NuclearModel:
      Model: FortranModel
      Name: QE_Spectral_Func
      ConfigFile: data/info_pke.data  
      FormFactorFile: "FormFactors.yml"
      Ward: None
  - NuclearModel:
      Model: FortranModel
      Name: Intf_Spectral_Func
      ConfigFile: data/intf_info.data  
      FormFactorFile: "FormFactors.yml"
      ModelParamsFile: "data/intf_params.yml"
      Ward: None
  - NuclearModel:
      Model: FortranModel
      Name: RES_Spectral_Func
      ConfigFile: data/info_pke.data  
      FormFactorFile: "FormFactors.yml"
      Ward: None

Nuclei:
  - Nucleus:
      Name: 12C
      Binding: 8.6
      Fermi Momentum: 225
      Density:
        File: data/c12.prova.txt
        FilePotential: data/realOP_12C_EDAI.dat
        Function: configuration
        Configs: data/configurations/QMC_configs.out.gz
      FermiGas: Local
      Potential: 
        Name: Schroedinger
        r0: 0.16
        Mode: 3

HardCuts:
  - Type: AngleTheta
    PIDs: 11
    range: [36.5, 38.5]

Backend:
  Name: Default
  Options: []
```

**Comment by jxi24** [comment]
@nastein. I did a quick run with the run card and looked at the output hepmc file. I do not see anything that pops out as incorrect. I do see a fair number of overweight points, but I did not train the vegas for super long so that could be the cause. I looked at the final cross-section reported at the end of the Achilles run and the total cross section from the last event from the hepmc file, and they are statistically consistent with each other. Could you send me the analysis script, so I can give that a try?

**Comment by nastein** [comment]
@jxi24 I've attached a short python script, it's saved as a .txt file so that I could upload it.
[achilles_3model_test.txt](https://github.com/AchillesGen/Achilles/files/15214991/achilles_3model_test.txt)

**Comment by jxi24** [comment]
It turns out that this issue is related to the random seed giving an abnormally large weighted event. Changing the seed removed the issue, so it is not with the number of models that are being used, but with the stability of the unweighting and the Vegas parameters. I will look into tuning these better to help try and minimize these points, and look into how to handle points that are significantly larger weights than the others in the future.
